### ISSUE TITLE
3D Tiles Next roadmap

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-native#386]
Roadmap issue to keep track of 3D Tiles Next extensions and their implementation status in Cesium Native.

See [3D Tiles Next README](https://github.com/CesiumGS/3d-tiles/tree/main/next) for more background on these extensions.

3D Tiles Next extensions:
* [x] [3DTILES_content_gltf](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf)
* [ ] [3DTILES_metadata](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata)
* [ ] [EXT_mesh_features](https://github.com/KhronosGroup/glTF/pull/2082) - Successor to [EXT_feature_metadata](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_feature_metadata) ([#281](https://github.com/CesiumGS/cesium-native/pull/281))
* [x] [3DTILES_implicit_tiling](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/extensions/3DTILES_implicit_tiling) - https://github.com/CesiumGS/cesium-native/issues/353
* [x] [3DTILES_bounding_volume_S2](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_bounding_volume_S2) - https://github.com/CesiumGS/cesium-native/issues/364
* [ ] [3DTILES_multiple_contents](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_multiple_contents)

Other useful glTF extensions

* [ ] [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) - https://github.com/CesiumGS/cesium-native/pull/290 (related)
* [x] [KHR_texture_basisu](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_texture_basisu/README.md)
* [ ] [EXT_meshopt_compression](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_meshopt_compression)
* [ ] [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_mesh_quantization)

The initial 3D Tiles Next datasets we want to show are OWT and CDB. The OWT base globe uses nearly all the 3D Tiles Next extensions. CDB data can be converted to 3D Tiles Next with the `--3d-tiles-next` flag once https://github.com/CesiumGS/cdb-to-3dtiles/pull/58 is merged. Datasets like Yemen have raster materials that are converted to feature ID textures.

OWT base globe | CDB with feature ID textures
--|--
![maxar](https://user-images.githubusercontent.com/915398/125845265-1f851af4-107c-417f-ab91-d54b1710d50e.jpg)|![cdb](https://user-images.githubusercontent.com/915398/125845255-90588d6f-424b-4f08-94e1-b7744ebd87b5.jpg)

**Comment by lilleyse** [comment]
Most of this has been implemented already, with the exception of multiple contents and `EXT_mesh_gpu_instancing` (which is being tracked [here](https://github.com/CesiumGS/cesium-native/issues/458)).
